// Mocks generated by Mockito 5.4.4 from annotations
// in hydrate/test/history_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:hydrate/core/domain/models/daily_summary.dart' as _i5;
import 'package:hydrate/core/domain/models/water_log.dart' as _i4;
import 'package:hydrate/core/domain/repositories/water_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IWaterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWaterRepository extends _i1.Mock implements _i2.IWaterRepository {
  MockIWaterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addWaterLog(_i4.WaterLog? log) =>
      (super.noSuchMethod(
            Invocation.method(#addWaterLog, [log]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.WaterLog>> getWaterLogsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getWaterLogsForDate, [date]),
            returnValue: _i3.Future<List<_i4.WaterLog>>.value(<_i4.WaterLog>[]),
          )
          as _i3.Future<List<_i4.WaterLog>>);

  @override
  _i3.Future<void> clearWaterLogsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#clearWaterLogsForDate, [date]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addDailySummary(_i5.DailySummary? summary) =>
      (super.noSuchMethod(
            Invocation.method(#addDailySummary, [summary]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.DailySummary?> getDailySummaryForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getDailySummaryForDate, [date]),
            returnValue: _i3.Future<_i5.DailySummary?>.value(),
          )
          as _i3.Future<_i5.DailySummary?>);

  @override
  _i3.Future<List<_i5.DailySummary>> getWaterIntakeHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getWaterIntakeHistory, []),
            returnValue: _i3.Future<List<_i5.DailySummary>>.value(
              <_i5.DailySummary>[],
            ),
          )
          as _i3.Future<List<_i5.DailySummary>>);
}
